# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_endereco_gateway.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto_endereco_gateway.proto\x12\x10\x65ndereco_gateway\"T\n\x0c\x45nderecoInfo\x12 \n\x18id_gateway_for_save_info\x18\x01 \x01(\t\x12\"\n\x1aport_gateway_for_save_info\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_endereco_gateway_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENDERECOINFO._serialized_start=50
  _ENDERECOINFO._serialized_end=134
# @@protoc_insertion_point(module_scope)
