// source: gateway.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.gateway.ComandoInfo', null, global);
goog.exportSymbol('proto.gateway.ComandoOperacao', null, global);
goog.exportSymbol('proto.gateway.Dispositivo', null, global);
goog.exportSymbol('proto.gateway.Requisicao', null, global);
goog.exportSymbol('proto.gateway.Requisicao.TipoCase', null, global);
goog.exportSymbol('proto.gateway.Resposta', null, global);
goog.exportSymbol('proto.gateway.Resposta.TipoCase', null, global);
goog.exportSymbol('proto.gateway.RespostaErro', null, global);
goog.exportSymbol('proto.gateway.RespostaOk', null, global);
goog.exportSymbol('proto.gateway.ResultadoAcao', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.Requisicao = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gateway.Requisicao.oneofGroups_);
};
goog.inherits(proto.gateway.Requisicao, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.Requisicao.displayName = 'proto.gateway.Requisicao';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.ComandoOperacao = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.ComandoOperacao, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.ComandoOperacao.displayName = 'proto.gateway.ComandoOperacao';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.ComandoInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.ComandoInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.ComandoInfo.displayName = 'proto.gateway.ComandoInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.Dispositivo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.Dispositivo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.Dispositivo.displayName = 'proto.gateway.Dispositivo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.ResultadoAcao = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.ResultadoAcao, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.ResultadoAcao.displayName = 'proto.gateway.ResultadoAcao';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.Resposta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gateway.Resposta.oneofGroups_);
};
goog.inherits(proto.gateway.Resposta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.Resposta.displayName = 'proto.gateway.Resposta';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.RespostaOk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.RespostaOk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.RespostaOk.displayName = 'proto.gateway.RespostaOk';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gateway.RespostaErro = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gateway.RespostaErro, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gateway.RespostaErro.displayName = 'proto.gateway.RespostaErro';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gateway.Requisicao.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.gateway.Requisicao.TipoCase = {
  TIPO_NOT_SET: 0,
  OPERACAO: 1,
  INFO: 2
};

/**
 * @return {proto.gateway.Requisicao.TipoCase}
 */
proto.gateway.Requisicao.prototype.getTipoCase = function() {
  return /** @type {proto.gateway.Requisicao.TipoCase} */(jspb.Message.computeOneofCase(this, proto.gateway.Requisicao.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.Requisicao.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.Requisicao.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.Requisicao} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Requisicao.toObject = function(includeInstance, msg) {
  var f, obj = {
    operacao: (f = msg.getOperacao()) && proto.gateway.ComandoOperacao.toObject(includeInstance, f),
    info: (f = msg.getInfo()) && proto.gateway.ComandoInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.Requisicao}
 */
proto.gateway.Requisicao.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.Requisicao;
  return proto.gateway.Requisicao.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.Requisicao} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.Requisicao}
 */
proto.gateway.Requisicao.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gateway.ComandoOperacao;
      reader.readMessage(value,proto.gateway.ComandoOperacao.deserializeBinaryFromReader);
      msg.setOperacao(value);
      break;
    case 2:
      var value = new proto.gateway.ComandoInfo;
      reader.readMessage(value,proto.gateway.ComandoInfo.deserializeBinaryFromReader);
      msg.setInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.Requisicao.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.Requisicao.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.Requisicao} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Requisicao.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperacao();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.gateway.ComandoOperacao.serializeBinaryToWriter
    );
  }
  f = message.getInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gateway.ComandoInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional ComandoOperacao operacao = 1;
 * @return {?proto.gateway.ComandoOperacao}
 */
proto.gateway.Requisicao.prototype.getOperacao = function() {
  return /** @type{?proto.gateway.ComandoOperacao} */ (
    jspb.Message.getWrapperField(this, proto.gateway.ComandoOperacao, 1));
};


/**
 * @param {?proto.gateway.ComandoOperacao|undefined} value
 * @return {!proto.gateway.Requisicao} returns this
*/
proto.gateway.Requisicao.prototype.setOperacao = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.gateway.Requisicao.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gateway.Requisicao} returns this
 */
proto.gateway.Requisicao.prototype.clearOperacao = function() {
  return this.setOperacao(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gateway.Requisicao.prototype.hasOperacao = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ComandoInfo info = 2;
 * @return {?proto.gateway.ComandoInfo}
 */
proto.gateway.Requisicao.prototype.getInfo = function() {
  return /** @type{?proto.gateway.ComandoInfo} */ (
    jspb.Message.getWrapperField(this, proto.gateway.ComandoInfo, 2));
};


/**
 * @param {?proto.gateway.ComandoInfo|undefined} value
 * @return {!proto.gateway.Requisicao} returns this
*/
proto.gateway.Requisicao.prototype.setInfo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.gateway.Requisicao.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gateway.Requisicao} returns this
 */
proto.gateway.Requisicao.prototype.clearInfo = function() {
  return this.setInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gateway.Requisicao.prototype.hasInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.ComandoOperacao.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.ComandoOperacao.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.ComandoOperacao} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ComandoOperacao.toObject = function(includeInstance, msg) {
  var f, obj = {
    operacao: jspb.Message.getFieldWithDefault(msg, 2, ""),
    parametrosMap: (f = msg.getParametrosMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.ComandoOperacao}
 */
proto.gateway.ComandoOperacao.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.ComandoOperacao;
  return proto.gateway.ComandoOperacao.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.ComandoOperacao} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.ComandoOperacao}
 */
proto.gateway.ComandoOperacao.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperacao(value);
      break;
    case 3:
      var value = msg.getParametrosMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.ComandoOperacao.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.ComandoOperacao.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.ComandoOperacao} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ComandoOperacao.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperacao();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getParametrosMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string operacao = 2;
 * @return {string}
 */
proto.gateway.ComandoOperacao.prototype.getOperacao = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.ComandoOperacao} returns this
 */
proto.gateway.ComandoOperacao.prototype.setOperacao = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * map<string, string> parametros = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.gateway.ComandoOperacao.prototype.getParametrosMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.gateway.ComandoOperacao} returns this
 */
proto.gateway.ComandoOperacao.prototype.clearParametrosMap = function() {
  this.getParametrosMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.ComandoInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.ComandoInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.ComandoInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ComandoInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    tipo: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dispositivo: (f = msg.getDispositivo()) && proto.gateway.Dispositivo.toObject(includeInstance, f),
    typeInputParametrosMap: (f = msg.getTypeInputParametrosMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.ComandoInfo}
 */
proto.gateway.ComandoInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.ComandoInfo;
  return proto.gateway.ComandoInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.ComandoInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.ComandoInfo}
 */
proto.gateway.ComandoInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTipo(value);
      break;
    case 2:
      var value = new proto.gateway.Dispositivo;
      reader.readMessage(value,proto.gateway.Dispositivo.deserializeBinaryFromReader);
      msg.setDispositivo(value);
      break;
    case 3:
      var value = msg.getTypeInputParametrosMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.ComandoInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.ComandoInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.ComandoInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ComandoInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTipo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDispositivo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gateway.Dispositivo.serializeBinaryToWriter
    );
  }
  f = message.getTypeInputParametrosMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string tipo = 1;
 * @return {string}
 */
proto.gateway.ComandoInfo.prototype.getTipo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.ComandoInfo} returns this
 */
proto.gateway.ComandoInfo.prototype.setTipo = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Dispositivo dispositivo = 2;
 * @return {?proto.gateway.Dispositivo}
 */
proto.gateway.ComandoInfo.prototype.getDispositivo = function() {
  return /** @type{?proto.gateway.Dispositivo} */ (
    jspb.Message.getWrapperField(this, proto.gateway.Dispositivo, 2));
};


/**
 * @param {?proto.gateway.Dispositivo|undefined} value
 * @return {!proto.gateway.ComandoInfo} returns this
*/
proto.gateway.ComandoInfo.prototype.setDispositivo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gateway.ComandoInfo} returns this
 */
proto.gateway.ComandoInfo.prototype.clearDispositivo = function() {
  return this.setDispositivo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gateway.ComandoInfo.prototype.hasDispositivo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * map<string, string> type_input_parametros = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.gateway.ComandoInfo.prototype.getTypeInputParametrosMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.gateway.ComandoInfo} returns this
 */
proto.gateway.ComandoInfo.prototype.clearTypeInputParametrosMap = function() {
  this.getTypeInputParametrosMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.Dispositivo.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.Dispositivo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.Dispositivo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Dispositivo.toObject = function(includeInstance, msg) {
  var f, obj = {
    tipo: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ipDevice: jspb.Message.getFieldWithDefault(msg, 2, ""),
    portDevice: jspb.Message.getFieldWithDefault(msg, 3, ""),
    nameDevice: jspb.Message.getFieldWithDefault(msg, 4, ""),
    statusDevice: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.Dispositivo}
 */
proto.gateway.Dispositivo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.Dispositivo;
  return proto.gateway.Dispositivo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.Dispositivo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.Dispositivo}
 */
proto.gateway.Dispositivo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTipo(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIpDevice(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPortDevice(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameDevice(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusDevice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.Dispositivo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.Dispositivo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.Dispositivo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Dispositivo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTipo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIpDevice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPortDevice();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNameDevice();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStatusDevice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string tipo = 1;
 * @return {string}
 */
proto.gateway.Dispositivo.prototype.getTipo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.Dispositivo} returns this
 */
proto.gateway.Dispositivo.prototype.setTipo = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ip_device = 2;
 * @return {string}
 */
proto.gateway.Dispositivo.prototype.getIpDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.Dispositivo} returns this
 */
proto.gateway.Dispositivo.prototype.setIpDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string port_device = 3;
 * @return {string}
 */
proto.gateway.Dispositivo.prototype.getPortDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.Dispositivo} returns this
 */
proto.gateway.Dispositivo.prototype.setPortDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string name_device = 4;
 * @return {string}
 */
proto.gateway.Dispositivo.prototype.getNameDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.Dispositivo} returns this
 */
proto.gateway.Dispositivo.prototype.setNameDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string status_device = 5;
 * @return {string}
 */
proto.gateway.Dispositivo.prototype.getStatusDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.Dispositivo} returns this
 */
proto.gateway.Dispositivo.prototype.setStatusDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.ResultadoAcao.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.ResultadoAcao.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.ResultadoAcao} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ResultadoAcao.toObject = function(includeInstance, msg) {
  var f, obj = {
    nameDevice: jspb.Message.getFieldWithDefault(msg, 1, ""),
    valueDevice: jspb.Message.getFieldWithDefault(msg, 2, ""),
    statusDevice: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tamanhoMensagem: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.ResultadoAcao}
 */
proto.gateway.ResultadoAcao.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.ResultadoAcao;
  return proto.gateway.ResultadoAcao.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.ResultadoAcao} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.ResultadoAcao}
 */
proto.gateway.ResultadoAcao.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameDevice(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValueDevice(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusDevice(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTamanhoMensagem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.ResultadoAcao.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.ResultadoAcao.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.ResultadoAcao} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.ResultadoAcao.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNameDevice();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValueDevice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatusDevice();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTamanhoMensagem();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string name_device = 1;
 * @return {string}
 */
proto.gateway.ResultadoAcao.prototype.getNameDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.ResultadoAcao} returns this
 */
proto.gateway.ResultadoAcao.prototype.setNameDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value_device = 2;
 * @return {string}
 */
proto.gateway.ResultadoAcao.prototype.getValueDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.ResultadoAcao} returns this
 */
proto.gateway.ResultadoAcao.prototype.setValueDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string status_device = 3;
 * @return {string}
 */
proto.gateway.ResultadoAcao.prototype.getStatusDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.ResultadoAcao} returns this
 */
proto.gateway.ResultadoAcao.prototype.setStatusDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 tamanho_mensagem = 4;
 * @return {number}
 */
proto.gateway.ResultadoAcao.prototype.getTamanhoMensagem = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.gateway.ResultadoAcao} returns this
 */
proto.gateway.ResultadoAcao.prototype.setTamanhoMensagem = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gateway.Resposta.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.gateway.Resposta.TipoCase = {
  TIPO_NOT_SET: 0,
  OK: 1,
  ERRO: 2
};

/**
 * @return {proto.gateway.Resposta.TipoCase}
 */
proto.gateway.Resposta.prototype.getTipoCase = function() {
  return /** @type {proto.gateway.Resposta.TipoCase} */(jspb.Message.computeOneofCase(this, proto.gateway.Resposta.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.Resposta.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.Resposta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.Resposta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Resposta.toObject = function(includeInstance, msg) {
  var f, obj = {
    ok: (f = msg.getOk()) && proto.gateway.RespostaOk.toObject(includeInstance, f),
    erro: (f = msg.getErro()) && proto.gateway.RespostaErro.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.Resposta}
 */
proto.gateway.Resposta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.Resposta;
  return proto.gateway.Resposta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.Resposta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.Resposta}
 */
proto.gateway.Resposta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.gateway.RespostaOk;
      reader.readMessage(value,proto.gateway.RespostaOk.deserializeBinaryFromReader);
      msg.setOk(value);
      break;
    case 2:
      var value = new proto.gateway.RespostaErro;
      reader.readMessage(value,proto.gateway.RespostaErro.deserializeBinaryFromReader);
      msg.setErro(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.Resposta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.Resposta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.Resposta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.Resposta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOk();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.gateway.RespostaOk.serializeBinaryToWriter
    );
  }
  f = message.getErro();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gateway.RespostaErro.serializeBinaryToWriter
    );
  }
};


/**
 * optional RespostaOk ok = 1;
 * @return {?proto.gateway.RespostaOk}
 */
proto.gateway.Resposta.prototype.getOk = function() {
  return /** @type{?proto.gateway.RespostaOk} */ (
    jspb.Message.getWrapperField(this, proto.gateway.RespostaOk, 1));
};


/**
 * @param {?proto.gateway.RespostaOk|undefined} value
 * @return {!proto.gateway.Resposta} returns this
*/
proto.gateway.Resposta.prototype.setOk = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.gateway.Resposta.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gateway.Resposta} returns this
 */
proto.gateway.Resposta.prototype.clearOk = function() {
  return this.setOk(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gateway.Resposta.prototype.hasOk = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RespostaErro erro = 2;
 * @return {?proto.gateway.RespostaErro}
 */
proto.gateway.Resposta.prototype.getErro = function() {
  return /** @type{?proto.gateway.RespostaErro} */ (
    jspb.Message.getWrapperField(this, proto.gateway.RespostaErro, 2));
};


/**
 * @param {?proto.gateway.RespostaErro|undefined} value
 * @return {!proto.gateway.Resposta} returns this
*/
proto.gateway.Resposta.prototype.setErro = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.gateway.Resposta.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gateway.Resposta} returns this
 */
proto.gateway.Resposta.prototype.clearErro = function() {
  return this.setErro(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gateway.Resposta.prototype.hasErro = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.RespostaOk.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.RespostaOk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.RespostaOk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.RespostaOk.toObject = function(includeInstance, msg) {
  var f, obj = {
    comando: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dadosMap: (f = msg.getDadosMap()) ? f.toObject(includeInstance, undefined) : [],
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.RespostaOk}
 */
proto.gateway.RespostaOk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.RespostaOk;
  return proto.gateway.RespostaOk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.RespostaOk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.RespostaOk}
 */
proto.gateway.RespostaOk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setComando(value);
      break;
    case 2:
      var value = msg.getDadosMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.RespostaOk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.RespostaOk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.RespostaOk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.RespostaOk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComando();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDadosMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getTimestamp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string comando = 1;
 * @return {string}
 */
proto.gateway.RespostaOk.prototype.getComando = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.RespostaOk} returns this
 */
proto.gateway.RespostaOk.prototype.setComando = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, string> dados = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.gateway.RespostaOk.prototype.getDadosMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.gateway.RespostaOk} returns this
 */
proto.gateway.RespostaOk.prototype.clearDadosMap = function() {
  this.getDadosMap().clear();
  return this;};


/**
 * optional string timestamp = 3;
 * @return {string}
 */
proto.gateway.RespostaOk.prototype.getTimestamp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.RespostaOk} returns this
 */
proto.gateway.RespostaOk.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gateway.RespostaErro.prototype.toObject = function(opt_includeInstance) {
  return proto.gateway.RespostaErro.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gateway.RespostaErro} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.RespostaErro.toObject = function(includeInstance, msg) {
  var f, obj = {
    comando: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mensagem: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 3, ""),
    detalhesMap: (f = msg.getDetalhesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gateway.RespostaErro}
 */
proto.gateway.RespostaErro.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gateway.RespostaErro;
  return proto.gateway.RespostaErro.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gateway.RespostaErro} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gateway.RespostaErro}
 */
proto.gateway.RespostaErro.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setComando(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMensagem(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimestamp(value);
      break;
    case 4:
      var value = msg.getDetalhesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gateway.RespostaErro.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gateway.RespostaErro.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gateway.RespostaErro} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gateway.RespostaErro.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComando();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMensagem();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimestamp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDetalhesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string comando = 1;
 * @return {string}
 */
proto.gateway.RespostaErro.prototype.getComando = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.RespostaErro} returns this
 */
proto.gateway.RespostaErro.prototype.setComando = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string mensagem = 2;
 * @return {string}
 */
proto.gateway.RespostaErro.prototype.getMensagem = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.RespostaErro} returns this
 */
proto.gateway.RespostaErro.prototype.setMensagem = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string timestamp = 3;
 * @return {string}
 */
proto.gateway.RespostaErro.prototype.getTimestamp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gateway.RespostaErro} returns this
 */
proto.gateway.RespostaErro.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, string> detalhes = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.gateway.RespostaErro.prototype.getDetalhesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.gateway.RespostaErro} returns this
 */
proto.gateway.RespostaErro.prototype.clearDetalhesMap = function() {
  this.getDetalhesMap().clear();
  return this;};


goog.object.extend(exports, proto.gateway);
