/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dispositivo.proto */

#ifndef PROTOBUF_C_dispositivo_2eproto__INCLUDED
#define PROTOBUF_C_dispositivo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Dispositivo__Requisicao Dispositivo__Requisicao;
typedef struct Dispositivo__RequisicaoLer Dispositivo__RequisicaoLer;
typedef struct Dispositivo__RequisicaoEscrever Dispositivo__RequisicaoEscrever;
typedef struct Dispositivo__ComandoOperacao Dispositivo__ComandoOperacao;
typedef struct Dispositivo__InfoDeviceClient Dispositivo__InfoDeviceClient;
typedef struct Dispositivo__InfoDeviceClient__ParametrosEntry Dispositivo__InfoDeviceClient__ParametrosEntry;
typedef struct Dispositivo__ReadDevice Dispositivo__ReadDevice;
typedef struct Dispositivo__ReadDevice__ParametrosEntry Dispositivo__ReadDevice__ParametrosEntry;
typedef struct Dispositivo__Resposta Dispositivo__Resposta;
typedef struct Dispositivo__RespostaOk Dispositivo__RespostaOk;
typedef struct Dispositivo__RespostaOk__DadosEntry Dispositivo__RespostaOk__DadosEntry;
typedef struct Dispositivo__RespostaErro Dispositivo__RespostaErro;
typedef struct Dispositivo__RespostaErro__DetalhesEntry Dispositivo__RespostaErro__DetalhesEntry;
typedef struct Dispositivo__EnderecoInfo Dispositivo__EnderecoInfo;


/* --- enums --- */

typedef enum _Dispositivo__ComandoOperacao__TipoOperacao {
  DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO__LER = 0,
  DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO__ESCREVER = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO)
} Dispositivo__ComandoOperacao__TipoOperacao;

/* --- messages --- */

typedef enum {
  DISPOSITIVO__REQUISICAO__TIPO__NOT_SET = 0,
  DISPOSITIVO__REQUISICAO__TIPO_LER = 3,
  DISPOSITIVO__REQUISICAO__TIPO_ESCREVER = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DISPOSITIVO__REQUISICAO__TIPO__CASE)
} Dispositivo__Requisicao__TipoCase;

/*
 * REQUISIÇÃO
 */
struct  Dispositivo__Requisicao
{
  ProtobufCMessage base;
  char *name_client;
  char *name_device;
  Dispositivo__Requisicao__TipoCase tipo_case;
  union {
    Dispositivo__RequisicaoEscrever *escrever;
    Dispositivo__RequisicaoLer *ler;
  };
};
#define DISPOSITIVO__REQUISICAO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__requisicao__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, DISPOSITIVO__REQUISICAO__TIPO__NOT_SET, {0} }


struct  Dispositivo__RequisicaoLer
{
  ProtobufCMessage base;
  /*
   * sempre LER
   */
  Dispositivo__ComandoOperacao *operacao;
};
#define DISPOSITIVO__REQUISICAO_LER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__requisicao_ler__descriptor) \
    , NULL }


struct  Dispositivo__RequisicaoEscrever
{
  ProtobufCMessage base;
  /*
   * sempre ESCREVER
   */
  Dispositivo__ComandoOperacao *operacao;
  Dispositivo__InfoDeviceClient *info_device;
};
#define DISPOSITIVO__REQUISICAO_ESCREVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__requisicao_escrever__descriptor) \
    , NULL, NULL }


/*
 * COMANDOS
 */
struct  Dispositivo__ComandoOperacao
{
  ProtobufCMessage base;
  Dispositivo__ComandoOperacao__TipoOperacao operacao;
};
#define DISPOSITIVO__COMANDO_OPERACAO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__comando_operacao__descriptor) \
    , DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO__LER }


struct  Dispositivo__InfoDeviceClient__ParametrosEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define DISPOSITIVO__INFO_DEVICE_CLIENT__PARAMETROS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__info_device_client__parametros_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DADOS DE ENTRADA
 */
struct  Dispositivo__InfoDeviceClient
{
  ProtobufCMessage base;
  char *status;
  char *type_device;
  size_t n_parametros;
  Dispositivo__InfoDeviceClient__ParametrosEntry **parametros;
};
#define DISPOSITIVO__INFO_DEVICE_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__info_device_client__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Dispositivo__ReadDevice__ParametrosEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define DISPOSITIVO__READ_DEVICE__PARAMETROS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__read_device__parametros_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * DADOS DE LEITURA
 */
struct  Dispositivo__ReadDevice
{
  ProtobufCMessage base;
  char *name_device;
  char *ip_device;
  uint32_t port_device;
  char *status;
  char *type_device;
  size_t n_parametros;
  Dispositivo__ReadDevice__ParametrosEntry **parametros;
};
#define DISPOSITIVO__READ_DEVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__read_device__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


typedef enum {
  DISPOSITIVO__RESPOSTA__TIPO__NOT_SET = 0,
  DISPOSITIVO__RESPOSTA__TIPO_OK = 1,
  DISPOSITIVO__RESPOSTA__TIPO_ERRO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DISPOSITIVO__RESPOSTA__TIPO__CASE)
} Dispositivo__Resposta__TipoCase;

/*
 * RESPOSTA
 */
struct  Dispositivo__Resposta
{
  ProtobufCMessage base;
  Dispositivo__Resposta__TipoCase tipo_case;
  union {
    Dispositivo__RespostaErro *erro;
    Dispositivo__RespostaOk *ok;
  };
};
#define DISPOSITIVO__RESPOSTA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__resposta__descriptor) \
    , DISPOSITIVO__RESPOSTA__TIPO__NOT_SET, {0} }


struct  Dispositivo__RespostaOk__DadosEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define DISPOSITIVO__RESPOSTA_OK__DADOS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__resposta_ok__dados_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Dispositivo__RespostaOk
{
  ProtobufCMessage base;
  char *comando;
  size_t n_dados;
  Dispositivo__RespostaOk__DadosEntry **dados;
  Dispositivo__ReadDevice *device_info;
};
#define DISPOSITIVO__RESPOSTA_OK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__resposta_ok__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, NULL }


struct  Dispositivo__RespostaErro__DetalhesEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define DISPOSITIVO__RESPOSTA_ERRO__DETALHES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__resposta_erro__detalhes_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Dispositivo__RespostaErro
{
  ProtobufCMessage base;
  char *comando;
  char *mensagem;
  size_t n_detalhes;
  Dispositivo__RespostaErro__DetalhesEntry **detalhes;
};
#define DISPOSITIVO__RESPOSTA_ERRO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__resposta_erro__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  Dispositivo__EnderecoInfo
{
  ProtobufCMessage base;
  char *id_gateway_for_save_info;
  char *port_gateway_for_save_info;
};
#define DISPOSITIVO__ENDERECO_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dispositivo__endereco_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Dispositivo__Requisicao methods */
void   dispositivo__requisicao__init
                     (Dispositivo__Requisicao         *message);
size_t dispositivo__requisicao__get_packed_size
                     (const Dispositivo__Requisicao   *message);
size_t dispositivo__requisicao__pack
                     (const Dispositivo__Requisicao   *message,
                      uint8_t             *out);
size_t dispositivo__requisicao__pack_to_buffer
                     (const Dispositivo__Requisicao   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__Requisicao *
       dispositivo__requisicao__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__requisicao__free_unpacked
                     (Dispositivo__Requisicao *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__RequisicaoLer methods */
void   dispositivo__requisicao_ler__init
                     (Dispositivo__RequisicaoLer         *message);
size_t dispositivo__requisicao_ler__get_packed_size
                     (const Dispositivo__RequisicaoLer   *message);
size_t dispositivo__requisicao_ler__pack
                     (const Dispositivo__RequisicaoLer   *message,
                      uint8_t             *out);
size_t dispositivo__requisicao_ler__pack_to_buffer
                     (const Dispositivo__RequisicaoLer   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__RequisicaoLer *
       dispositivo__requisicao_ler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__requisicao_ler__free_unpacked
                     (Dispositivo__RequisicaoLer *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__RequisicaoEscrever methods */
void   dispositivo__requisicao_escrever__init
                     (Dispositivo__RequisicaoEscrever         *message);
size_t dispositivo__requisicao_escrever__get_packed_size
                     (const Dispositivo__RequisicaoEscrever   *message);
size_t dispositivo__requisicao_escrever__pack
                     (const Dispositivo__RequisicaoEscrever   *message,
                      uint8_t             *out);
size_t dispositivo__requisicao_escrever__pack_to_buffer
                     (const Dispositivo__RequisicaoEscrever   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__RequisicaoEscrever *
       dispositivo__requisicao_escrever__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__requisicao_escrever__free_unpacked
                     (Dispositivo__RequisicaoEscrever *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__ComandoOperacao methods */
void   dispositivo__comando_operacao__init
                     (Dispositivo__ComandoOperacao         *message);
size_t dispositivo__comando_operacao__get_packed_size
                     (const Dispositivo__ComandoOperacao   *message);
size_t dispositivo__comando_operacao__pack
                     (const Dispositivo__ComandoOperacao   *message,
                      uint8_t             *out);
size_t dispositivo__comando_operacao__pack_to_buffer
                     (const Dispositivo__ComandoOperacao   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__ComandoOperacao *
       dispositivo__comando_operacao__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__comando_operacao__free_unpacked
                     (Dispositivo__ComandoOperacao *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__InfoDeviceClient__ParametrosEntry methods */
void   dispositivo__info_device_client__parametros_entry__init
                     (Dispositivo__InfoDeviceClient__ParametrosEntry         *message);
/* Dispositivo__InfoDeviceClient methods */
void   dispositivo__info_device_client__init
                     (Dispositivo__InfoDeviceClient         *message);
size_t dispositivo__info_device_client__get_packed_size
                     (const Dispositivo__InfoDeviceClient   *message);
size_t dispositivo__info_device_client__pack
                     (const Dispositivo__InfoDeviceClient   *message,
                      uint8_t             *out);
size_t dispositivo__info_device_client__pack_to_buffer
                     (const Dispositivo__InfoDeviceClient   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__InfoDeviceClient *
       dispositivo__info_device_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__info_device_client__free_unpacked
                     (Dispositivo__InfoDeviceClient *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__ReadDevice__ParametrosEntry methods */
void   dispositivo__read_device__parametros_entry__init
                     (Dispositivo__ReadDevice__ParametrosEntry         *message);
/* Dispositivo__ReadDevice methods */
void   dispositivo__read_device__init
                     (Dispositivo__ReadDevice         *message);
size_t dispositivo__read_device__get_packed_size
                     (const Dispositivo__ReadDevice   *message);
size_t dispositivo__read_device__pack
                     (const Dispositivo__ReadDevice   *message,
                      uint8_t             *out);
size_t dispositivo__read_device__pack_to_buffer
                     (const Dispositivo__ReadDevice   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__ReadDevice *
       dispositivo__read_device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__read_device__free_unpacked
                     (Dispositivo__ReadDevice *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__Resposta methods */
void   dispositivo__resposta__init
                     (Dispositivo__Resposta         *message);
size_t dispositivo__resposta__get_packed_size
                     (const Dispositivo__Resposta   *message);
size_t dispositivo__resposta__pack
                     (const Dispositivo__Resposta   *message,
                      uint8_t             *out);
size_t dispositivo__resposta__pack_to_buffer
                     (const Dispositivo__Resposta   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__Resposta *
       dispositivo__resposta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__resposta__free_unpacked
                     (Dispositivo__Resposta *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__RespostaOk__DadosEntry methods */
void   dispositivo__resposta_ok__dados_entry__init
                     (Dispositivo__RespostaOk__DadosEntry         *message);
/* Dispositivo__RespostaOk methods */
void   dispositivo__resposta_ok__init
                     (Dispositivo__RespostaOk         *message);
size_t dispositivo__resposta_ok__get_packed_size
                     (const Dispositivo__RespostaOk   *message);
size_t dispositivo__resposta_ok__pack
                     (const Dispositivo__RespostaOk   *message,
                      uint8_t             *out);
size_t dispositivo__resposta_ok__pack_to_buffer
                     (const Dispositivo__RespostaOk   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__RespostaOk *
       dispositivo__resposta_ok__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__resposta_ok__free_unpacked
                     (Dispositivo__RespostaOk *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__RespostaErro__DetalhesEntry methods */
void   dispositivo__resposta_erro__detalhes_entry__init
                     (Dispositivo__RespostaErro__DetalhesEntry         *message);
/* Dispositivo__RespostaErro methods */
void   dispositivo__resposta_erro__init
                     (Dispositivo__RespostaErro         *message);
size_t dispositivo__resposta_erro__get_packed_size
                     (const Dispositivo__RespostaErro   *message);
size_t dispositivo__resposta_erro__pack
                     (const Dispositivo__RespostaErro   *message,
                      uint8_t             *out);
size_t dispositivo__resposta_erro__pack_to_buffer
                     (const Dispositivo__RespostaErro   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__RespostaErro *
       dispositivo__resposta_erro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__resposta_erro__free_unpacked
                     (Dispositivo__RespostaErro *message,
                      ProtobufCAllocator *allocator);
/* Dispositivo__EnderecoInfo methods */
void   dispositivo__endereco_info__init
                     (Dispositivo__EnderecoInfo         *message);
size_t dispositivo__endereco_info__get_packed_size
                     (const Dispositivo__EnderecoInfo   *message);
size_t dispositivo__endereco_info__pack
                     (const Dispositivo__EnderecoInfo   *message,
                      uint8_t             *out);
size_t dispositivo__endereco_info__pack_to_buffer
                     (const Dispositivo__EnderecoInfo   *message,
                      ProtobufCBuffer     *buffer);
Dispositivo__EnderecoInfo *
       dispositivo__endereco_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dispositivo__endereco_info__free_unpacked
                     (Dispositivo__EnderecoInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dispositivo__Requisicao_Closure)
                 (const Dispositivo__Requisicao *message,
                  void *closure_data);
typedef void (*Dispositivo__RequisicaoLer_Closure)
                 (const Dispositivo__RequisicaoLer *message,
                  void *closure_data);
typedef void (*Dispositivo__RequisicaoEscrever_Closure)
                 (const Dispositivo__RequisicaoEscrever *message,
                  void *closure_data);
typedef void (*Dispositivo__ComandoOperacao_Closure)
                 (const Dispositivo__ComandoOperacao *message,
                  void *closure_data);
typedef void (*Dispositivo__InfoDeviceClient__ParametrosEntry_Closure)
                 (const Dispositivo__InfoDeviceClient__ParametrosEntry *message,
                  void *closure_data);
typedef void (*Dispositivo__InfoDeviceClient_Closure)
                 (const Dispositivo__InfoDeviceClient *message,
                  void *closure_data);
typedef void (*Dispositivo__ReadDevice__ParametrosEntry_Closure)
                 (const Dispositivo__ReadDevice__ParametrosEntry *message,
                  void *closure_data);
typedef void (*Dispositivo__ReadDevice_Closure)
                 (const Dispositivo__ReadDevice *message,
                  void *closure_data);
typedef void (*Dispositivo__Resposta_Closure)
                 (const Dispositivo__Resposta *message,
                  void *closure_data);
typedef void (*Dispositivo__RespostaOk__DadosEntry_Closure)
                 (const Dispositivo__RespostaOk__DadosEntry *message,
                  void *closure_data);
typedef void (*Dispositivo__RespostaOk_Closure)
                 (const Dispositivo__RespostaOk *message,
                  void *closure_data);
typedef void (*Dispositivo__RespostaErro__DetalhesEntry_Closure)
                 (const Dispositivo__RespostaErro__DetalhesEntry *message,
                  void *closure_data);
typedef void (*Dispositivo__RespostaErro_Closure)
                 (const Dispositivo__RespostaErro *message,
                  void *closure_data);
typedef void (*Dispositivo__EnderecoInfo_Closure)
                 (const Dispositivo__EnderecoInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dispositivo__requisicao__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__requisicao_ler__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__requisicao_escrever__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__comando_operacao__descriptor;
extern const ProtobufCEnumDescriptor    dispositivo__comando_operacao__tipo_operacao__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__info_device_client__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__info_device_client__parametros_entry__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__read_device__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__read_device__parametros_entry__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__resposta__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__resposta_ok__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__resposta_ok__dados_entry__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__resposta_erro__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__resposta_erro__detalhes_entry__descriptor;
extern const ProtobufCMessageDescriptor dispositivo__endereco_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_dispositivo_2eproto__INCLUDED */
