/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dispositivo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dispositivo.pb-c.h"
void   dispositivo__requisicao__init
                     (Dispositivo__Requisicao         *message)
{
  static const Dispositivo__Requisicao init_value = DISPOSITIVO__REQUISICAO__INIT;
  *message = init_value;
}
size_t dispositivo__requisicao__get_packed_size
                     (const Dispositivo__Requisicao *message)
{
  assert(message->base.descriptor == &dispositivo__requisicao__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__requisicao__pack
                     (const Dispositivo__Requisicao *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__requisicao__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__requisicao__pack_to_buffer
                     (const Dispositivo__Requisicao *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__requisicao__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__Requisicao *
       dispositivo__requisicao__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__Requisicao *)
     protobuf_c_message_unpack (&dispositivo__requisicao__descriptor,
                                allocator, len, data);
}
void   dispositivo__requisicao__free_unpacked
                     (Dispositivo__Requisicao *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__requisicao__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__requisicao_ler__init
                     (Dispositivo__RequisicaoLer         *message)
{
  static const Dispositivo__RequisicaoLer init_value = DISPOSITIVO__REQUISICAO_LER__INIT;
  *message = init_value;
}
size_t dispositivo__requisicao_ler__get_packed_size
                     (const Dispositivo__RequisicaoLer *message)
{
  assert(message->base.descriptor == &dispositivo__requisicao_ler__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__requisicao_ler__pack
                     (const Dispositivo__RequisicaoLer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__requisicao_ler__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__requisicao_ler__pack_to_buffer
                     (const Dispositivo__RequisicaoLer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__requisicao_ler__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__RequisicaoLer *
       dispositivo__requisicao_ler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__RequisicaoLer *)
     protobuf_c_message_unpack (&dispositivo__requisicao_ler__descriptor,
                                allocator, len, data);
}
void   dispositivo__requisicao_ler__free_unpacked
                     (Dispositivo__RequisicaoLer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__requisicao_ler__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__requisicao_escrever__init
                     (Dispositivo__RequisicaoEscrever         *message)
{
  static const Dispositivo__RequisicaoEscrever init_value = DISPOSITIVO__REQUISICAO_ESCREVER__INIT;
  *message = init_value;
}
size_t dispositivo__requisicao_escrever__get_packed_size
                     (const Dispositivo__RequisicaoEscrever *message)
{
  assert(message->base.descriptor == &dispositivo__requisicao_escrever__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__requisicao_escrever__pack
                     (const Dispositivo__RequisicaoEscrever *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__requisicao_escrever__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__requisicao_escrever__pack_to_buffer
                     (const Dispositivo__RequisicaoEscrever *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__requisicao_escrever__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__RequisicaoEscrever *
       dispositivo__requisicao_escrever__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__RequisicaoEscrever *)
     protobuf_c_message_unpack (&dispositivo__requisicao_escrever__descriptor,
                                allocator, len, data);
}
void   dispositivo__requisicao_escrever__free_unpacked
                     (Dispositivo__RequisicaoEscrever *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__requisicao_escrever__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__comando_operacao__init
                     (Dispositivo__ComandoOperacao         *message)
{
  static const Dispositivo__ComandoOperacao init_value = DISPOSITIVO__COMANDO_OPERACAO__INIT;
  *message = init_value;
}
size_t dispositivo__comando_operacao__get_packed_size
                     (const Dispositivo__ComandoOperacao *message)
{
  assert(message->base.descriptor == &dispositivo__comando_operacao__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__comando_operacao__pack
                     (const Dispositivo__ComandoOperacao *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__comando_operacao__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__comando_operacao__pack_to_buffer
                     (const Dispositivo__ComandoOperacao *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__comando_operacao__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__ComandoOperacao *
       dispositivo__comando_operacao__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__ComandoOperacao *)
     protobuf_c_message_unpack (&dispositivo__comando_operacao__descriptor,
                                allocator, len, data);
}
void   dispositivo__comando_operacao__free_unpacked
                     (Dispositivo__ComandoOperacao *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__comando_operacao__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__info_device_client__parametros_entry__init
                     (Dispositivo__InfoDeviceClient__ParametrosEntry         *message)
{
  static const Dispositivo__InfoDeviceClient__ParametrosEntry init_value = DISPOSITIVO__INFO_DEVICE_CLIENT__PARAMETROS_ENTRY__INIT;
  *message = init_value;
}
void   dispositivo__info_device_client__init
                     (Dispositivo__InfoDeviceClient         *message)
{
  static const Dispositivo__InfoDeviceClient init_value = DISPOSITIVO__INFO_DEVICE_CLIENT__INIT;
  *message = init_value;
}
size_t dispositivo__info_device_client__get_packed_size
                     (const Dispositivo__InfoDeviceClient *message)
{
  assert(message->base.descriptor == &dispositivo__info_device_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__info_device_client__pack
                     (const Dispositivo__InfoDeviceClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__info_device_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__info_device_client__pack_to_buffer
                     (const Dispositivo__InfoDeviceClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__info_device_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__InfoDeviceClient *
       dispositivo__info_device_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__InfoDeviceClient *)
     protobuf_c_message_unpack (&dispositivo__info_device_client__descriptor,
                                allocator, len, data);
}
void   dispositivo__info_device_client__free_unpacked
                     (Dispositivo__InfoDeviceClient *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__info_device_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__read_device__parametros_entry__init
                     (Dispositivo__ReadDevice__ParametrosEntry         *message)
{
  static const Dispositivo__ReadDevice__ParametrosEntry init_value = DISPOSITIVO__READ_DEVICE__PARAMETROS_ENTRY__INIT;
  *message = init_value;
}
void   dispositivo__read_device__init
                     (Dispositivo__ReadDevice         *message)
{
  static const Dispositivo__ReadDevice init_value = DISPOSITIVO__READ_DEVICE__INIT;
  *message = init_value;
}
size_t dispositivo__read_device__get_packed_size
                     (const Dispositivo__ReadDevice *message)
{
  assert(message->base.descriptor == &dispositivo__read_device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__read_device__pack
                     (const Dispositivo__ReadDevice *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__read_device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__read_device__pack_to_buffer
                     (const Dispositivo__ReadDevice *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__read_device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__ReadDevice *
       dispositivo__read_device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__ReadDevice *)
     protobuf_c_message_unpack (&dispositivo__read_device__descriptor,
                                allocator, len, data);
}
void   dispositivo__read_device__free_unpacked
                     (Dispositivo__ReadDevice *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__read_device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__resposta__init
                     (Dispositivo__Resposta         *message)
{
  static const Dispositivo__Resposta init_value = DISPOSITIVO__RESPOSTA__INIT;
  *message = init_value;
}
size_t dispositivo__resposta__get_packed_size
                     (const Dispositivo__Resposta *message)
{
  assert(message->base.descriptor == &dispositivo__resposta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__resposta__pack
                     (const Dispositivo__Resposta *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__resposta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__resposta__pack_to_buffer
                     (const Dispositivo__Resposta *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__resposta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__Resposta *
       dispositivo__resposta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__Resposta *)
     protobuf_c_message_unpack (&dispositivo__resposta__descriptor,
                                allocator, len, data);
}
void   dispositivo__resposta__free_unpacked
                     (Dispositivo__Resposta *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__resposta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__resposta_ok__dados_entry__init
                     (Dispositivo__RespostaOk__DadosEntry         *message)
{
  static const Dispositivo__RespostaOk__DadosEntry init_value = DISPOSITIVO__RESPOSTA_OK__DADOS_ENTRY__INIT;
  *message = init_value;
}
void   dispositivo__resposta_ok__init
                     (Dispositivo__RespostaOk         *message)
{
  static const Dispositivo__RespostaOk init_value = DISPOSITIVO__RESPOSTA_OK__INIT;
  *message = init_value;
}
size_t dispositivo__resposta_ok__get_packed_size
                     (const Dispositivo__RespostaOk *message)
{
  assert(message->base.descriptor == &dispositivo__resposta_ok__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__resposta_ok__pack
                     (const Dispositivo__RespostaOk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__resposta_ok__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__resposta_ok__pack_to_buffer
                     (const Dispositivo__RespostaOk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__resposta_ok__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__RespostaOk *
       dispositivo__resposta_ok__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__RespostaOk *)
     protobuf_c_message_unpack (&dispositivo__resposta_ok__descriptor,
                                allocator, len, data);
}
void   dispositivo__resposta_ok__free_unpacked
                     (Dispositivo__RespostaOk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__resposta_ok__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__resposta_erro__detalhes_entry__init
                     (Dispositivo__RespostaErro__DetalhesEntry         *message)
{
  static const Dispositivo__RespostaErro__DetalhesEntry init_value = DISPOSITIVO__RESPOSTA_ERRO__DETALHES_ENTRY__INIT;
  *message = init_value;
}
void   dispositivo__resposta_erro__init
                     (Dispositivo__RespostaErro         *message)
{
  static const Dispositivo__RespostaErro init_value = DISPOSITIVO__RESPOSTA_ERRO__INIT;
  *message = init_value;
}
size_t dispositivo__resposta_erro__get_packed_size
                     (const Dispositivo__RespostaErro *message)
{
  assert(message->base.descriptor == &dispositivo__resposta_erro__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__resposta_erro__pack
                     (const Dispositivo__RespostaErro *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__resposta_erro__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__resposta_erro__pack_to_buffer
                     (const Dispositivo__RespostaErro *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__resposta_erro__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__RespostaErro *
       dispositivo__resposta_erro__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__RespostaErro *)
     protobuf_c_message_unpack (&dispositivo__resposta_erro__descriptor,
                                allocator, len, data);
}
void   dispositivo__resposta_erro__free_unpacked
                     (Dispositivo__RespostaErro *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__resposta_erro__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dispositivo__endereco_info__init
                     (Dispositivo__EnderecoInfo         *message)
{
  static const Dispositivo__EnderecoInfo init_value = DISPOSITIVO__ENDERECO_INFO__INIT;
  *message = init_value;
}
size_t dispositivo__endereco_info__get_packed_size
                     (const Dispositivo__EnderecoInfo *message)
{
  assert(message->base.descriptor == &dispositivo__endereco_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dispositivo__endereco_info__pack
                     (const Dispositivo__EnderecoInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dispositivo__endereco_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dispositivo__endereco_info__pack_to_buffer
                     (const Dispositivo__EnderecoInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dispositivo__endereco_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dispositivo__EnderecoInfo *
       dispositivo__endereco_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dispositivo__EnderecoInfo *)
     protobuf_c_message_unpack (&dispositivo__endereco_info__descriptor,
                                allocator, len, data);
}
void   dispositivo__endereco_info__free_unpacked
                     (Dispositivo__EnderecoInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dispositivo__endereco_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dispositivo__requisicao__field_descriptors[4] =
{
  {
    "name_client",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__Requisicao, name_client),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name_device",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__Requisicao, name_device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ler",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__Requisicao, tipo_case),
    offsetof(Dispositivo__Requisicao, ler),
    &dispositivo__requisicao_ler__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "escrever",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__Requisicao, tipo_case),
    offsetof(Dispositivo__Requisicao, escrever),
    &dispositivo__requisicao_escrever__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__requisicao__field_indices_by_name[] = {
  3,   /* field[3] = escrever */
  2,   /* field[2] = ler */
  0,   /* field[0] = name_client */
  1,   /* field[1] = name_device */
};
static const ProtobufCIntRange dispositivo__requisicao__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dispositivo__requisicao__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.Requisicao",
  "Requisicao",
  "Dispositivo__Requisicao",
  "dispositivo",
  sizeof(Dispositivo__Requisicao),
  4,
  dispositivo__requisicao__field_descriptors,
  dispositivo__requisicao__field_indices_by_name,
  1,  dispositivo__requisicao__number_ranges,
  (ProtobufCMessageInit) dispositivo__requisicao__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__requisicao_ler__field_descriptors[1] =
{
  {
    "operacao",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RequisicaoLer, operacao),
    &dispositivo__comando_operacao__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__requisicao_ler__field_indices_by_name[] = {
  0,   /* field[0] = operacao */
};
static const ProtobufCIntRange dispositivo__requisicao_ler__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dispositivo__requisicao_ler__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RequisicaoLer",
  "RequisicaoLer",
  "Dispositivo__RequisicaoLer",
  "dispositivo",
  sizeof(Dispositivo__RequisicaoLer),
  1,
  dispositivo__requisicao_ler__field_descriptors,
  dispositivo__requisicao_ler__field_indices_by_name,
  1,  dispositivo__requisicao_ler__number_ranges,
  (ProtobufCMessageInit) dispositivo__requisicao_ler__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__requisicao_escrever__field_descriptors[2] =
{
  {
    "operacao",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RequisicaoEscrever, operacao),
    &dispositivo__comando_operacao__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info_device",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RequisicaoEscrever, info_device),
    &dispositivo__info_device_client__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__requisicao_escrever__field_indices_by_name[] = {
  1,   /* field[1] = info_device */
  0,   /* field[0] = operacao */
};
static const ProtobufCIntRange dispositivo__requisicao_escrever__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__requisicao_escrever__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RequisicaoEscrever",
  "RequisicaoEscrever",
  "Dispositivo__RequisicaoEscrever",
  "dispositivo",
  sizeof(Dispositivo__RequisicaoEscrever),
  2,
  dispositivo__requisicao_escrever__field_descriptors,
  dispositivo__requisicao_escrever__field_indices_by_name,
  1,  dispositivo__requisicao_escrever__number_ranges,
  (ProtobufCMessageInit) dispositivo__requisicao_escrever__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dispositivo__comando_operacao__tipo_operacao__enum_values_by_number[2] =
{
  { "LER", "DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO__LER", 0 },
  { "ESCREVER", "DISPOSITIVO__COMANDO_OPERACAO__TIPO_OPERACAO__ESCREVER", 1 },
};
static const ProtobufCIntRange dispositivo__comando_operacao__tipo_operacao__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dispositivo__comando_operacao__tipo_operacao__enum_values_by_name[2] =
{
  { "ESCREVER", 1 },
  { "LER", 0 },
};
const ProtobufCEnumDescriptor dispositivo__comando_operacao__tipo_operacao__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dispositivo.ComandoOperacao.TipoOperacao",
  "TipoOperacao",
  "Dispositivo__ComandoOperacao__TipoOperacao",
  "dispositivo",
  2,
  dispositivo__comando_operacao__tipo_operacao__enum_values_by_number,
  2,
  dispositivo__comando_operacao__tipo_operacao__enum_values_by_name,
  1,
  dispositivo__comando_operacao__tipo_operacao__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dispositivo__comando_operacao__field_descriptors[1] =
{
  {
    "operacao",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ComandoOperacao, operacao),
    &dispositivo__comando_operacao__tipo_operacao__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__comando_operacao__field_indices_by_name[] = {
  0,   /* field[0] = operacao */
};
static const ProtobufCIntRange dispositivo__comando_operacao__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dispositivo__comando_operacao__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.ComandoOperacao",
  "ComandoOperacao",
  "Dispositivo__ComandoOperacao",
  "dispositivo",
  sizeof(Dispositivo__ComandoOperacao),
  1,
  dispositivo__comando_operacao__field_descriptors,
  dispositivo__comando_operacao__field_indices_by_name,
  1,  dispositivo__comando_operacao__number_ranges,
  (ProtobufCMessageInit) dispositivo__comando_operacao__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__info_device_client__parametros_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__InfoDeviceClient__ParametrosEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__InfoDeviceClient__ParametrosEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__info_device_client__parametros_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dispositivo__info_device_client__parametros_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__info_device_client__parametros_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.InfoDeviceClient.ParametrosEntry",
  "ParametrosEntry",
  "Dispositivo__InfoDeviceClient__ParametrosEntry",
  "dispositivo",
  sizeof(Dispositivo__InfoDeviceClient__ParametrosEntry),
  2,
  dispositivo__info_device_client__parametros_entry__field_descriptors,
  dispositivo__info_device_client__parametros_entry__field_indices_by_name,
  1,  dispositivo__info_device_client__parametros_entry__number_ranges,
  (ProtobufCMessageInit) dispositivo__info_device_client__parametros_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__info_device_client__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__InfoDeviceClient, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type_device",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__InfoDeviceClient, type_device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parametros",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__InfoDeviceClient, n_parametros),
    offsetof(Dispositivo__InfoDeviceClient, parametros),
    &dispositivo__info_device_client__parametros_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__info_device_client__field_indices_by_name[] = {
  2,   /* field[2] = parametros */
  0,   /* field[0] = status */
  1,   /* field[1] = type_device */
};
static const ProtobufCIntRange dispositivo__info_device_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dispositivo__info_device_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.InfoDeviceClient",
  "InfoDeviceClient",
  "Dispositivo__InfoDeviceClient",
  "dispositivo",
  sizeof(Dispositivo__InfoDeviceClient),
  3,
  dispositivo__info_device_client__field_descriptors,
  dispositivo__info_device_client__field_indices_by_name,
  1,  dispositivo__info_device_client__number_ranges,
  (ProtobufCMessageInit) dispositivo__info_device_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__read_device__parametros_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice__ParametrosEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice__ParametrosEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__read_device__parametros_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dispositivo__read_device__parametros_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__read_device__parametros_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.ReadDevice.ParametrosEntry",
  "ParametrosEntry",
  "Dispositivo__ReadDevice__ParametrosEntry",
  "dispositivo",
  sizeof(Dispositivo__ReadDevice__ParametrosEntry),
  2,
  dispositivo__read_device__parametros_entry__field_descriptors,
  dispositivo__read_device__parametros_entry__field_indices_by_name,
  1,  dispositivo__read_device__parametros_entry__number_ranges,
  (ProtobufCMessageInit) dispositivo__read_device__parametros_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__read_device__field_descriptors[6] =
{
  {
    "name_device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice, name_device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_device",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice, ip_device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port_device",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice, port_device),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type_device",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__ReadDevice, type_device),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parametros",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__ReadDevice, n_parametros),
    offsetof(Dispositivo__ReadDevice, parametros),
    &dispositivo__read_device__parametros_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__read_device__field_indices_by_name[] = {
  1,   /* field[1] = ip_device */
  0,   /* field[0] = name_device */
  5,   /* field[5] = parametros */
  2,   /* field[2] = port_device */
  3,   /* field[3] = status */
  4,   /* field[4] = type_device */
};
static const ProtobufCIntRange dispositivo__read_device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dispositivo__read_device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.ReadDevice",
  "ReadDevice",
  "Dispositivo__ReadDevice",
  "dispositivo",
  sizeof(Dispositivo__ReadDevice),
  6,
  dispositivo__read_device__field_descriptors,
  dispositivo__read_device__field_indices_by_name,
  1,  dispositivo__read_device__number_ranges,
  (ProtobufCMessageInit) dispositivo__read_device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__resposta__field_descriptors[2] =
{
  {
    "ok",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__Resposta, tipo_case),
    offsetof(Dispositivo__Resposta, ok),
    &dispositivo__resposta_ok__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "erro",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__Resposta, tipo_case),
    offsetof(Dispositivo__Resposta, erro),
    &dispositivo__resposta_erro__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__resposta__field_indices_by_name[] = {
  1,   /* field[1] = erro */
  0,   /* field[0] = ok */
};
static const ProtobufCIntRange dispositivo__resposta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__resposta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.Resposta",
  "Resposta",
  "Dispositivo__Resposta",
  "dispositivo",
  sizeof(Dispositivo__Resposta),
  2,
  dispositivo__resposta__field_descriptors,
  dispositivo__resposta__field_indices_by_name,
  1,  dispositivo__resposta__number_ranges,
  (ProtobufCMessageInit) dispositivo__resposta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__resposta_ok__dados_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaOk__DadosEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaOk__DadosEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__resposta_ok__dados_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dispositivo__resposta_ok__dados_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__resposta_ok__dados_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RespostaOk.DadosEntry",
  "DadosEntry",
  "Dispositivo__RespostaOk__DadosEntry",
  "dispositivo",
  sizeof(Dispositivo__RespostaOk__DadosEntry),
  2,
  dispositivo__resposta_ok__dados_entry__field_descriptors,
  dispositivo__resposta_ok__dados_entry__field_indices_by_name,
  1,  dispositivo__resposta_ok__dados_entry__number_ranges,
  (ProtobufCMessageInit) dispositivo__resposta_ok__dados_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__resposta_ok__field_descriptors[3] =
{
  {
    "comando",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaOk, comando),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dados",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__RespostaOk, n_dados),
    offsetof(Dispositivo__RespostaOk, dados),
    &dispositivo__resposta_ok__dados_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_info",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaOk, device_info),
    &dispositivo__read_device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__resposta_ok__field_indices_by_name[] = {
  0,   /* field[0] = comando */
  1,   /* field[1] = dados */
  2,   /* field[2] = device_info */
};
static const ProtobufCIntRange dispositivo__resposta_ok__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dispositivo__resposta_ok__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RespostaOk",
  "RespostaOk",
  "Dispositivo__RespostaOk",
  "dispositivo",
  sizeof(Dispositivo__RespostaOk),
  3,
  dispositivo__resposta_ok__field_descriptors,
  dispositivo__resposta_ok__field_indices_by_name,
  1,  dispositivo__resposta_ok__number_ranges,
  (ProtobufCMessageInit) dispositivo__resposta_ok__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__resposta_erro__detalhes_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaErro__DetalhesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaErro__DetalhesEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__resposta_erro__detalhes_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dispositivo__resposta_erro__detalhes_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__resposta_erro__detalhes_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RespostaErro.DetalhesEntry",
  "DetalhesEntry",
  "Dispositivo__RespostaErro__DetalhesEntry",
  "dispositivo",
  sizeof(Dispositivo__RespostaErro__DetalhesEntry),
  2,
  dispositivo__resposta_erro__detalhes_entry__field_descriptors,
  dispositivo__resposta_erro__detalhes_entry__field_indices_by_name,
  1,  dispositivo__resposta_erro__detalhes_entry__number_ranges,
  (ProtobufCMessageInit) dispositivo__resposta_erro__detalhes_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__resposta_erro__field_descriptors[3] =
{
  {
    "comando",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaErro, comando),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mensagem",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__RespostaErro, mensagem),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detalhes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Dispositivo__RespostaErro, n_detalhes),
    offsetof(Dispositivo__RespostaErro, detalhes),
    &dispositivo__resposta_erro__detalhes_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__resposta_erro__field_indices_by_name[] = {
  0,   /* field[0] = comando */
  2,   /* field[2] = detalhes */
  1,   /* field[1] = mensagem */
};
static const ProtobufCIntRange dispositivo__resposta_erro__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dispositivo__resposta_erro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.RespostaErro",
  "RespostaErro",
  "Dispositivo__RespostaErro",
  "dispositivo",
  sizeof(Dispositivo__RespostaErro),
  3,
  dispositivo__resposta_erro__field_descriptors,
  dispositivo__resposta_erro__field_indices_by_name,
  1,  dispositivo__resposta_erro__number_ranges,
  (ProtobufCMessageInit) dispositivo__resposta_erro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dispositivo__endereco_info__field_descriptors[2] =
{
  {
    "id_gateway_for_save_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__EnderecoInfo, id_gateway_for_save_info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port_gateway_for_save_info",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dispositivo__EnderecoInfo, port_gateway_for_save_info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dispositivo__endereco_info__field_indices_by_name[] = {
  0,   /* field[0] = id_gateway_for_save_info */
  1,   /* field[1] = port_gateway_for_save_info */
};
static const ProtobufCIntRange dispositivo__endereco_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dispositivo__endereco_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dispositivo.EnderecoInfo",
  "EnderecoInfo",
  "Dispositivo__EnderecoInfo",
  "dispositivo",
  sizeof(Dispositivo__EnderecoInfo),
  2,
  dispositivo__endereco_info__field_descriptors,
  dispositivo__endereco_info__field_indices_by_name,
  1,  dispositivo__endereco_info__number_ranges,
  (ProtobufCMessageInit) dispositivo__endereco_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
